# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0200ec955845185f8ca5a76351e98e45b38c6796e732201980fc3c1de0fe2e4f49a93e5e8f35c283b097a2d1ef0b963aa1fcb77bc20893ff88579c79374f6711
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  aws_key: <%= ENV["AWS_KEY"] %>
  aws_secret:  <%= ENV["AWS_SECRET"] %>
  aws_dir:  <%= ENV["AWS_DIR"] %>
test:
  secret_key_base: e4c51b124f04193eca04bb1d95a54cd204fc0e6449486eb9e8fb1ea0e6e18838d16287620073508b702682c0ae41e02b6dba0095abf1a110bcfe9b0fad358406
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  aws_key: <%= ENV["AWS_KEY"] %>
  aws_secret:  <%= ENV["AWS_SECRET"] %>
  aws_dir:  <%= ENV["AWS_DIR"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  aws_key: <%= ENV["AWS_KEY"] %>
  aws_secret:  <%= ENV["AWS_SECRET"] %>
  aws_dir:  <%= ENV["AWS_DIR"] %>
